spring:
  application:
    name: climalert

weather-api:
  base-url: http://api.weatherapi.com/v1
  api-key: ${WEATHER_API_KEY:101301148f7a47809b102710260107}   # default propia; se puede pisar con la env var WEATHER_API_KEY
  location: Buenos Aires

climalert:
  frecuencias:
    consulta-rate-ms: 300000
    eval-rate-ms: 60000
  alerta:
    destinatarios:
      - admin@clima.com
      - emergencias@clima.com
      - meteorologia@clima.com
